[database]

# older versions of flit supported postgres.  that has been removed.  only
# sqlite is supported at the moment.
type = 'sqlite'

# if relative path, it is relative to the directory containing this
# configuration file.
filepath = 'results.sqlite'

[[hosts]]

# TODO: add documentation here for each element.

name = 'lilyofthevalley.llnl.gov'
flit_path = '/Users/bentley8/git/FLiT/scripts/flitcli/flit.py'
config_dir = '/Users/bentley8/git/FLiT/scripts/flitcli/config'

# The settings for "make dev"
[hosts.dev_build]
# compiler_name must be found in [[hosts.compilers]] list under name attribute
# but the optimization level and switches do not need to be in the compiler list
compiler_name = 'g++'
optimization_level = '-O2'
switches = '-funsafe-math-optimizations'

# The ground truth compilation to use in analysis
[hosts.ground_truth]
# compiler needs to match the name field for one of this host's hosts.compilers
# The optimization level needs to be part of the list of optimization_levels
# and the switch needs to be a string of compiler flags from the switches list.
# TODO: make use of hosts.ground_truth
compiler_name = 'g++'
optimization_level = '-O0'
switches = ''

  [[hosts.compilers]]

  # TODO: figure out how to specify path for each host machine
  # TODO: what if the compilers list is part of the host?

  # binary can be an absolute path, relative path, or binary name (found in
  # PATH).  If you want to specify a compiler in the same directory as this
  # config file, prepend with a "./" (e.g. "./my-compiler")
  binary = 'g++'
  # TODO: this is not yet used...
  # It is recommended to include version number in the name.  This is how the
  # compiler will be recognized in the results, and subsequently in the
  # database and analysis.
  name = 'g++'
  # TODO: implement these supported types
  # There are a few supported types: [ gcc, intel, clang, cuda ]
  type = 'gcc'
  optimization_levels = [
    '-O0',
    '-O1',
    '-O2',
    '-O3',
    #'-Ofast',
    #'-O...' ?
  ]
  switches_list = [
    '-fassociative-math',
    '-mavx',
    '-mp1',
    '-mavx2 -mfma',
    ''
    # ...
  ]
  

