[database]
type = 'sqlite'
filepath = 'results.sqlite'

[[hosts]]
name = 'bihexal'
flit_path = '/home/mbentley/git/FLiT/scripts/flitcli/flit.py'
config_dir = '/home/mbentley/git/FLiT/scripts/flitcli/config'

[hosts.dev_build]
compiler_name = 'icpc'
optimization_level = '-O0'
switches = ''

[hosts.ground_truth]
compiler_name = 'g++'
optimization_level = '-O0'
switches = ''

  [[hosts.compilers]]
  binary = '/opt/intel/bin/icpc'
  name = 'icpc'
  type = 'intel'

  [[hosts.compilers]]
  binary = '/usr/bin/g++'
  name = 'g++'
  type = 'gcc'

  [[hosts.compilers]]
  binary = '/usr/bin/clang++'
  name = 'clang++'
  type = 'clang'

