[database]
type = 'sqlite'
filepath = 'results.sqlite'

[[hosts]]

[hosts.dev_build]
compiler_name = 'g++'
optimization_level = '-O2'
switches = '-funsafe-math-optimizations'

[hosts.ground_truth]
compiler_name = 'g++'
optimization_level = '-O0'
switches = ''

  [[hosts.compilers]]
  binary = '/opt/intel/bin/icpc'
  name = 'icpc'
  type = 'intel'

  [[hosts.compilers]]
  binary = '/usr/bin/g++'
  name = 'g++'
  type = 'gcc'

  [[hosts.compilers]]
  binary = '/usr/bin/clang++'
  name = 'clang++'
  type = 'clang'

